version: '3.9'

services:
  # Web Viewer for Penrose SVG output
  penrose-viewer:
    image: nginx:alpine
    container_name: penrose-viewer
    ports:
      - "8888:80"
    volumes:
      - ~/.penrose:/usr/share/nginx/html:ro
      - ./penrose-viewer.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - data-science
    labels:
      mcp-toolset: "true"
      category: "viewer"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Simple test web server to demonstrate setup
  test-api:
    image: kennethreitz/httpbin:latest
    container_name: test-api
    ports:
      - "8888:80"
    networks:
      - data-science
    labels:
      mcp-toolset: "true"
      category: "test"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/get"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  data-science:
    driver: bridge

volumes:
