version: '3.9'

services:
  # Web UI: Unified NGINX gateway
  nginx-gateway:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "8888:80"
    volumes:
      - ./web-dashboard:/usr/share/nginx/html:ro
      - ./nginx-server.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - data-science
    labels:
      mcp-toolset: "true"
      category: "viewer"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  data-science:
    driver: bridge

volumes:
  data-explorer-work:
