---
apiVersion: v1
kind: Secret
metadata:
  name: hf-credentials
  namespace: data-science
type: Opaque
stringData:
  token: ""
---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: huggingface-mcp
  namespace: data-science
  labels:
    mcp-toolset: "true"
    discovery: "true"
spec:
  image: shreyas/huggingface-mcp-server:latest
  imagePullPolicy: IfNotPresent
  transport:
    type: streamable-http
  env:
    - name: HF_TOKEN
      valueFrom:
        secretKeyRef:
          name: hf-credentials
          key: token
          optional: true
  ports:
    - name: http
      containerPort: 8001
      protocol: TCP
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  livenessProbe:
    httpGet:
      path: /health
      port: 8001
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /health
      port: 8001
    initialDelaySeconds: 10
    periodSeconds: 10
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop:
        - ALL
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - huggingface-mcp
            topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: huggingface-mcp
  namespace: data-science
  labels:
    mcp-toolset: "true"
spec:
  type: ClusterIP
  selector:
    app: huggingface-mcp
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
