---
apiVersion: v1
kind: Secret
metadata:
  name: datahub-credentials
  namespace: data-science
type: Opaque
stringData:
  gms-url: ""
  gms-token: ""
---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: datahub-mcp
  namespace: data-science
  labels:
    mcp-toolset: "true"
    governance: "true"
spec:
  image: acryldata/mcp-server-datahub:latest
  imagePullPolicy: IfNotPresent
  transport:
    type: streamable-http
  env:
    - name: DATAHUB_GMS_URL
      valueFrom:
        secretKeyRef:
          name: datahub-credentials
          key: gms-url
          optional: true
    - name: DATAHUB_GMS_TOKEN
      valueFrom:
        secretKeyRef:
          name: datahub-credentials
          key: gms-token
          optional: true
  ports:
    - name: http
      containerPort: 8005
      protocol: TCP
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  livenessProbe:
    httpGet:
      path: /health
      port: 8005
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /health
      port: 8005
    initialDelaySeconds: 15
    periodSeconds: 15
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop:
        - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: datahub-mcp
  namespace: data-science
  labels:
    mcp-toolset: "true"
spec:
  type: ClusterIP
  selector:
    app: datahub-mcp
  ports:
    - name: http
      port: 8005
      targetPort: 8005
      protocol: TCP
